# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: docker-hub

steps:
- script: |
    docker build --tag $(Build.Repository.Name):$(Build.SourceVersion) .
  displayName: 'Build Docker image'

- script: |
    echo "$(dockerPassword)" | docker login --username "$(dockerId)" --password-stdin
  displayName: 'Authenticate with Docker Hub'

- script: |
    docker tag $(Build.Repository.Name):$(Build.SourceVersion) $(Build.Repository.Name):latest
  displayName: 'Tag image with :latest'

- script: |
    docker push $(Build.Repository.Name):$(Build.SourceVersion)
    docker push $(Build.Repository.Name):latest
  displayName: 'Push Docker image to Docker Hub'